import Foundation

/// Metadata about a file attachment shown in messages and composer
struct FileAttachmentDetail: Codable, Identifiable, Hashable {
    let id: String
    let name: String
    let mimeType: String?
    let sizeBytes: Int?
    let width: Int?
    let height: Int?
    let url: URL?
}

/// Output of a tool call (optionally includes generated files)
struct ToolResult: Codable, Hashable {
    let output: String?
    let files: [GeneratedFile]?
}

/// A file generated by a tool (e.g., an image or document)
struct GeneratedFile: Codable, Identifiable, Hashable {
    let id: String
    let name: String
    let url: URL?
}

/// An image parsed from markdown content
struct ParsedImage: Codable, Identifiable, Hashable {
    let id: String
    let url: URL
    let alt: String?
}

/// Detailed tool call information surfaced in the UI
struct ToolCallDetail: Codable, Identifiable, Hashable {
    enum Status: String, Codable { case pending, approved, rejected, completed, failed }
    let id: String
    let name: String
    let args: [String: AnyJSONValue]
    let result: AnyJSONValue? // Changed from ToolResult? to handle dict/string/any type
    let error: String?
    let status: Status
}

/// Rich message model used by the enhanced chat UI components
struct EnhancedChatMessage: Identifiable, Hashable {
    let id: String
    let threadId: String
    let role: String // user|assistant|system
    let content: String

    // Agent / provider
    let agentRole: String?
    let model: String?
    let provider: String?

    // Usage and cost
    let tokens: Int?
    let cost: Double?

    // Rich content
    let thoughts: [String]?
    let toolCalls: [ToolCallDetail]?
    let attachments: [FileAttachmentDetail]?
    let images: [ParsedImage]?
    let generatedFiles: [GeneratedFile]?

    let createdAt: Date?
}
